### ISSUE TITLE
Subscription: redirection failure

### ISSUE THREAD

**Issue by belgoros** [wunsh/wunsh-site#17]
Привет!

При оформлении подписки, вернулось 404 от [Mailchimp](https://wunsh.us14.list-manage.com/subscribe/post?u=c81ca3d4693f62db7f7f67c71&id=a192e2dfef).
<img width="365" alt="Screenshot 2022-10-31 at 12 53 52" src="https://user-images.githubusercontent.com/83579/199027997-39638dd7-4cb0-4e95-93f8-2fd747c2923b.png">

**Comment by jarosluv** [comment]
Hey @belgoros! Sorry, the Wunsh mailing list is no longer available.
